BPL:
    nr_cl: 4
    nr_deg: 3

FL1:
    nr_cl: 3
    nr_deg: 3

SPD:
    nr_cl: 4
    nr_deg: 3

ISA:
    nr_cl: 4
    nr_deg: 3

GB:
    nr_cl: 4
    nr_deg: 3
DE:
    nr_cl: 2
    nr_deg: 3
ELC:
    nr_cl: 3
    nr_deg: 3
PL:
    nr_cl: 2
    nr_deg: 2